# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/koil/Library/CloudStorage/OneDrive-HKUSTConnect/3000E/isdn3000e-lab7

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/koil/Library/CloudStorage/OneDrive-HKUSTConnect/3000E/isdn3000e-lab7

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/koil/Library/CloudStorage/OneDrive-HKUSTConnect/3000E/isdn3000e-lab7/CMakeFiles /Users/koil/Library/CloudStorage/OneDrive-HKUSTConnect/3000E/isdn3000e-lab7//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/koil/Library/CloudStorage/OneDrive-HKUSTConnect/3000E/isdn3000e-lab7/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named isdn3000e_lab7

# Build rule for target.
isdn3000e_lab7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 isdn3000e_lab7
.PHONY : isdn3000e_lab7

# fast build rule for target.
isdn3000e_lab7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/build
.PHONY : isdn3000e_lab7/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/main.cpp.s
.PHONY : main.cpp.s

tasks/task1.o: tasks/task1.cpp.o
.PHONY : tasks/task1.o

# target to build an object file
tasks/task1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/tasks/task1.cpp.o
.PHONY : tasks/task1.cpp.o

tasks/task1.i: tasks/task1.cpp.i
.PHONY : tasks/task1.i

# target to preprocess a source file
tasks/task1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/tasks/task1.cpp.i
.PHONY : tasks/task1.cpp.i

tasks/task1.s: tasks/task1.cpp.s
.PHONY : tasks/task1.s

# target to generate assembly for a file
tasks/task1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/tasks/task1.cpp.s
.PHONY : tasks/task1.cpp.s

tasks/task2.o: tasks/task2.cpp.o
.PHONY : tasks/task2.o

# target to build an object file
tasks/task2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/tasks/task2.cpp.o
.PHONY : tasks/task2.cpp.o

tasks/task2.i: tasks/task2.cpp.i
.PHONY : tasks/task2.i

# target to preprocess a source file
tasks/task2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/tasks/task2.cpp.i
.PHONY : tasks/task2.cpp.i

tasks/task2.s: tasks/task2.cpp.s
.PHONY : tasks/task2.s

# target to generate assembly for a file
tasks/task2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/isdn3000e_lab7.dir/build.make CMakeFiles/isdn3000e_lab7.dir/tasks/task2.cpp.s
.PHONY : tasks/task2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... isdn3000e_lab7"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tasks/task1.o"
	@echo "... tasks/task1.i"
	@echo "... tasks/task1.s"
	@echo "... tasks/task2.o"
	@echo "... tasks/task2.i"
	@echo "... tasks/task2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

